<!DOCTYPE html>
<html lang="pt-br">
    <head>
        <title>Rodrigo Moura de Campos</title>
        
        <link rel="stylesheet" type="text/css" href="css/estilo.css">
    </head>
    <body>


         <h1><b><center>Rodrigo Moura de Campos</center></b></h1>     
                    
        Brasileiro, 30 anos<br/>
        Estado Civil: Solteiro<br />
        Rua Frei Fabiano, 106 apto. 502 
        Engenho Novo, Rio de Janeiro - Brasil<br />
        Contatos: (21) 98712-4775 / (21) 3065-4020<br />
        E-mail: rodrigo.camposs@yahoo.com.br<br />
                    
          <img id="fototopo" src="imagens/foto_Rodrigo.jpg"   />

            
                        
            <br /><h2>Objetivo</h2>
                <hr>
                Contribuir com o crescimento e desenvolvimento da empresa utilizando meus conhecimentos, com ética e profissionalismo, priorizando a qualidade do serviço.<br />
                        
               <br /><h2>Perfil profissional</h2>
                <hr>
                Pró-ativo, boa capacidade para aprendizagem, facilidade para trabalhar em equipe e responsabilidade . Busco o aperfeiçoamento e o desenvolvimento profissional.<br />
                
                
            <br /><h2>Formação Acadêmica</h2>
                <hr>
                <ul>
                    <li><b>Sistema de Informação</b></li>
                Universidade Veiga de Almeida –  Cursando o 1º Período – Previsão: 2023<br />
                
                    <br /><li><b>Ensino Médio Técnico – Técnico em Eletrônica</b></li>
                Colégio Graham Bell – Concluído: 2009<br />
                
                <br /><li><b>Ensino Médio </b></li>
                Colégio Estadual João Alfredo – Concluído: 2007<br />
                    </ul>
                
                <br /><h2>Experiência Profissional</h2>
                <hr>
                <b>Oi / Telemar Norte Lesta S/A – Maio/2013 – Até a presente data Empresa de grande porte – Nacional – Segmento em Telecomunicações</b>   <br />Cargo: Técnico em Telecomunicações 2
                    
                <ul>
                    <li>Gerenciamento remoto, atuando como ponto Suporte Nível II no tratamento de falhas e aos técnicos locais.</li>
                    <li>Operação e Manutenção remota na rede móvel da Oi, com intuito de garantir a qualidade do sistema.</li>
                    <li>Atuando nas tecnologias: Nokia (2G, 3G e 4G), Siemens (2G), Ericsson (2G e 4G), Huawei (2G e 3G) em suas respectivas plataformas: NetAct, Radio Comander, M200,  Através das ferramentas: Granite, SGFT, Citrix, Winfiol, SecureCRT, Altaia, Traffic News e Traffic Views, para tentativa de correção das falhas, configuração e análise de desempenho da rede.</li>
                    <li>Atuando como ponto focal da equipe, auxiliando no tratamento das falhas e elaboração de procedimentos.</li>
                    <li>Análise dos indicadores mensais buscando alcançar as metas estabelecidas pela operadora.</li>
                    
                    </ul>
                    
                    <b>Nokia Siemens Network – Outubro/2009 – Maio/2013 Empresa de grande porte – Multinacional – Segmento em Telecomunicações</b>
                    <br />Cargo: Técnico em Telecomunicações 1
                    
                <ul>
                        <li>Gerenciamento remoto, atuando como Suporte Nível II no tratamento de falhas e aos técnicos locais.</li>
                        <li>Operação e Manutenção remota na rede GSM BSS Oi,  a fim de garantir a qualidade do sistema.</li>
                        <li>Atuando nas tecnologias: Nokia (2G e 3G) e Siemens(2G) em suas respectivas plataformas: NetAct e Radio Comander. Através das ferramentas: Vantive, SGFT, Citrix, Satcel, Traffic News e Traffic Views, para tentativa de correção das falhas, configuração e análise de desempenho da rede.</li>
                    
                    </ul>    
                
                <br /><h2>Cursos Complementares</h2>
                    <hr>            
                <ul>
                        <li><b>Desenhista Mecânico</b> - Senai - Unidade Triagem (Novembro/2018) - Concluído.</li>
                        <li><b>Inglês</b> - Curso Yes – Unidade Méier (Julho/2009) - Concluído</li>
                        <li><b>Informática</b> - Curso CHR (Junho/2007) - Concluído.</li>
                        
                        </ul>
                
                <br /><h2>Idiomas</h2>
                    <hr>
                    
                    <ul>
                        <li><b>Inglês</b> - Leitura, Escrita e Conversação fluente.</li>
                    
                    </ul>
                    
                    <br /><h2>Redes Sociais:</h2>
                    <hr>
                    <p><a href="https://www.linkedin.com/in/rodrigo-moura-de-campos-b1367084/" target="_blank"><img src="imagens/lk.png" width="25" height="25" ></a>

                    
                    
    </body>
    
</html>
